### ISSUE TITLE
One-line header possible?

### ISSUE THREAD

**Issue by jpmens** [shuque/checkzoneserial#2]
Would you entertain the idea of having `checkzoneserial` issue a one-line header before the list of serial/name servers instead of the two it issues now?

So, instead of

```console
$ checkzoneserial example.org
## Zone: example.org.
## Time: 2022-11-12T10:28:27UTC
     2022091140 b.iana-servers.net. 199.43.133.53 96.74ms
     2022091140 a.iana-servers.net. 199.43.135.53 104.36ms
     2022091140 b.iana-servers.net. 2001:500:8d::53 104.41ms
     2022091140 a.iana-servers.net. 2001:500:8f::53 105.66ms
```

something a bit more compact, as in

```console
$ checkzoneserial example.org
example.org. 2022-11-12T10:28:27UTC
     2022091140 b.iana-servers.net. 199.43.133.53 96.74ms
     2022091140 a.iana-servers.net. 199.43.135.53 104.36ms
     2022091140 b.iana-servers.net. 2001:500:8d::53 104.41ms
     2022091140 a.iana-servers.net. 2001:500:8f::53 105.66ms
```

I can't imagine that people who use `checkzoneserial` wouldn't know what those two values are. :-)

**Comment by shuque** [comment]
Yes, that's a reasonable suggestion. Let me quickly check to see if we have any scripts that make assumptions about the current header format first. If not, I can make that change.

**Comment by shuque** [comment]
Done, with commit 43991752f501702dcf4fd32e691b921903b7aba2

**Comment by jpmens** [comment]
Thank you.
